#!/bin/bash
#
# This script is for configuring alacrity on the authors' machines
# NOTE: assumes no spaces in paths; if spaces exist in your
#       environment, you must fix this file for yourself

SRCDIR=`dirname ${BASH_SOURCE[0]}`
if [ `hostname | cut -c 1-4` == "sith" ]; then

    ########
    # Sith #
    ########
    source /etc/profile.d/modules.sh
    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`

    if [ -z "$TARGET" ]; then
        echo "Cannot determine Programming environment. Exit"
        exit 1
    fi
    echo "Configure on SITH for $TARGET env. for user ${USER}"
    INSTALL_DIR=build.$TARGET
    FULL_INSTALL_PATH=$(cd $(dirname "${INSTALL_DIR}") && pwd)/$(basename "${INSTALL_DIR}")

    if [ "$TARGET" == "pgi" ]; then
        export CC=pgCC
        export CXX=pgCC
        CFLAGS="-g -fPIC"
        CXXFLAGS="-g -fPIC"
    elif [ "$TARGET" == "gnu" ]; then
        export CC=gcc
        export CXX=g++
        CFLAGS="-g -fPIC"
        CXXFLAGS="-g -fPIC -fno-exceptions -fno-rtti"
    elif [ "$TARGET" == "intel" ]; then
        export CC=icc
        export CXX=icpc
        CFLAGS="-g -fPIC"
        CXXFLAGS="-g -fPIC"
    else
        echo "TARGET must be pgi or gnu or intel. Use default"
        unset CC
        unset CXX
    fi

    echo ${SRCDIR}/configure --prefix=${FULL_INSTALL_PATH}
    CFLAGS=${CFLAGS} CXXFLAGS=${CXXFLAGS} ${SRCDIR}/configure --prefix=${FULL_INSTALL_PATH}

elif [ `hostname | cut -c 1-4` == "dyn9" -o `hostname | cut -c 1-3` == "pnb" ]; then

    #######
    # Mac #
    #######
    echo "Configure on Mac"
    # Installed Homebrew, gcc/gfortran 5.3.0 and OpenMPI 1.10.2 in /usr/local
    # But should work with default mpicc and gcc, using --disable-fortran or with Homebrew gfortran
    #
    USE_GCC5=false
    if [ $USE_GCC5 == "true" ]; then
        # If want to use gcc/gfortran 5.3.0
        INSTALL_DIR=/opt/alacrity/gcc5
        export CC=/usr/local/bin/gcc-5
        export CXX=/usr/local/bin/g++-5
    else
        # If want to use clang
        INSTALL_DIR=/opt/alacrity/clang
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
    fi
    CFLAGS="-g -fPIC -fno-common -Wall"
    CXXFLAGS="-g -fPIC -fno-exceptions -fno-rtti"
    echo ${SRCDIR}/configure --prefix=${INSTALL_DIR}
    CFLAGS=${CFLAGS} CXXFLAGS=${CXXFLAGS} ${SRCDIR}/configure --prefix=${INSTALL_DIR}

elif [ `hostname | cut -c 1-7` == "adiosVM" ]; then

    #######################
    # ADIOS Virtual Box #
    #######################
    echo "Configure on ADIOS VirtualBox."
    CFLAGS="-g -fPIC -fno-common -Wall"
    CXXFLAGS="-g -fPIC -fno-exceptions -fno-rtti"
    INSTALL_DIR=/opt/alacrity
    echo ${SRCDIR}/configure --prefix=${INSTALL_DIR}
    CFLAGS=${CFLAGS} CXXFLAGS=${CXXFLAGS} ${SRCDIR}/configure --prefix=${INSTALL_DIR}

else
    echo "Could not determine what machine is this. Configure with default settings"
    CFLAGS="-g -fPIC"
    CXXFLAGS="-g -fPIC -fno-exceptions -fno-rtti"
    CFLAGS=${CFLAGS} CXXFLAGS=${CXXFLAGS} ${SRCDIR}/configure 
fi
